### ISSUE TITLE
Stellina Night plan

### ISSUE THREAD

**Issue by lmesousa** [DeepSkyWorkflows/Stellinator#2]
Issues about Stellina Plan My Night

**Comment by lmesousa** [comment]
Does Stellinator process Stellina Night plans?

**Comment by JeremyLikness** [comment]
Hi, @lmesousa not currently but shouldn't be difficult for me to add. I've rewritten some other tools to be more flexible and handle more cases and can bring some of that to Stellinator.

**Comment by lmesousa** [comment]
Hi

Thanks for your answer.

Luís Miguel Sousa

A terça, 25/07/2023, 04:54, Jeremy Likness ***@***.***>
escreveu:
